apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: aspnet-lab
spec:
  replicas: 3
  selector:
    matchLabels:
      service: webapp
  template:
    metadata:
      labels:
        app: aspnet-lab
        service: webapp
    spec:
      containers:
        - name: webapp
          image: acrdemo02.azurecr.io/aspnet-lab:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:5000
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: aspnet-lab
    service: webapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    service: webapp
