name: Demo Aspnet

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  AZURE_WEBAPP_NAME: Demo-GithubActions    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root


jobs:
  build:
    
    runs-on: ubuntu-latest
    name: Build

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  deploy:
    needs: [build]
    runs-on: ubuntu-18.04
    name: Deploy Web App
    steps:
    - name: azure-resource-login
      uses: Azure/azure-resource-login-action@v1.0.0
      with:
        # Azure credentials for the service principal to log in
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        # Canonical resource url for what you want the token for
        resource-type-name: Microsoft.Web
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

