name: Demo WebApp

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  AZURE_WEBAPP: '.'
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build 
      run: dotnet build --configuration Release --no-restore

    - name: dotnet publish
      run: dotnet publish -c Release -o ${{ env.AZURE_WEBAPP }}/output

    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: artifact
        path: output/
        
  deploy:
    needs: build
    name: Deploy Web App
    runs-on: ubuntu-latest
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.10
      with:
        name: artifact
        path: ${{ env.AZURE_WEBAPP }}/output

    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: Demo-githubactions01
        publish-profile: ${{ secrets.PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP }}/output




















