name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    name: Build Aspnet
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v2.1.0
      with:
        dotnet-version: 5.0.x
        
    - name: Install dependecies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: dotnet publish
      run: dotnet publish -c Release -o ./output
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: artifact
        path: output/
    
