name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build aspnet
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2.1.0
      with:
         dotnet-version: 5.0.x
         
    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Publish
      run: dotnet publish -c Release -o ./output
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: artifact
        path: output/
        
      
    
   
   
      
    
