name: Demo terraform

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  deploy-iac:
    runs-on: ubuntu-18.04
    name: Deploy IAC
    steps:
    - name: "Checkout"
      uses: actions/checkout@master
    - uses: hashicorp/setup-terraform@v1

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: false
      
    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate

    - name: Terraform Plan
      id: plan
      run: terraform plan
      continue-on-error: false
