name: WebApp Docker

on: 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY_NAME: aspnetlab
  REPOSITORY_NAME: aspnetlab
  APP_NAME: aspnet-lab

permissions:
      id-token: write
      contents: read
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        registry: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }} 
        password: ${{ secrets.REGISTRY_PASSWORD }}
         
    - name: Build and push Docker image
      run: |
        docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.REPOSITORY_NAME }}:${{ github.sha }}
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.REPOSITORY_NAME }}:${{ github.sha }}
      working-directory: ./

  deploy:
    environment: dev
    needs: build
    runs-on: ubuntu-latest
    steps:   
    - name: Azure Login
      uses: Azure/login@v1
      with:
#        creds: ${{ secrets.AZURE_CREDENTIALS }}
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
       
    - name: Deploy Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ env.APP_NAME }}
        images: ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.REPOSITORY_NAME }}:${{ github.sha }}

